/*
   Copyright 2026 OhMyDitzzy

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/// A standard EXIF tag identifier.
///
/// Tag values are 16-bit unsigned integers. This enum covers all tags defined
/// in the EXIF 2.3 / TIFF 6.0 specifications. Unknown tags are represented by
/// `Tag::Unknown(u16)` so they are preserved rather than discarded.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Tag {
    // IFD0 / IFD1 - Primary image info
    ImageWidth,
    ImageLength,
    BitsPerSample,
    Compression,
    PhotometricInterpretation,
    ImageDescription,
    Make,
    Model,
    StripOffsets,
    Orientation,
    SamplesPerPixel,
    RowsPerStrip,
    StripByteCounts,
    XResolution,
    YResolution,
    PlanarConfiguration,
    ResolutionUnit,
    TransferFunction,
    Software,
    DateTime,
    Artist,
    WhitePoint,
    PrimaryChromaticities,
    YCbCrCoefficients,
    YCbCrSubSampling,
    YCbCrPositioning,
    ReferenceBlackWhite,
    Copyright,
    ExifIfdPointer,
    GpsInfoIfdPointer,

    // Exif IFD - Capture settings
    ExifVersion,
    DateTimeOriginal,
    DateTimeDigitized,
    OffsetTime,
    OffsetTimeOriginal,
    OffsetTimeDigitized,
    ComponentsConfiguration,
    CompressedBitsPerPixel,
    ShutterSpeedValue,
    ApertureValue,
    BrightnessValue,
    ExposureBiasValue,
    MaxApertureValue,
    SubjectDistance,
    MeteringMode,
    LightSource,
    Flash,
    FocalLength,
    MakerNote,
    UserComment,
    SubSecTime,
    SubSecTimeOriginal,
    SubSecTimeDigitized,
    FlashPixVersion,
    ColorSpace,
    PixelXDimension,
    PixelYDimension,
    RelatedSoundFile,
    InteroperabilityIfdPointer,
    FlashEnergy,
    FocalPlaneXResolution,
    FocalPlaneYResolution,
    FocalPlaneResolutionUnit,
    SubjectLocation,
    ExposureIndex,
    SensingMethod,
    FileSource,
    SceneType,
    CfaPattern,
    CustomRendered,
    ExposureMode,
    WhiteBalance,
    DigitalZoomRatio,
    FocalLengthIn35mmFilm,
    SceneCaptureType,
    GainControl,
    Contrast,
    Saturation,
    Sharpness,
    DeviceSettingDescription,
    SubjectDistanceRange,
    ImageUniqueId,
    CameraOwnerName,
    BodySerialNumber,
    LensSpecification,
    LensMake,
    LensModel,
    LensSerialNumber,
    ExposureTime,
    FNumber,
    ExposureProgram,
    SpectralSensitivity,
    IsoSpeedRatings,
    SensitivityType,
    StandardOutputSensitivity,
    RecommendedExposureIndex,
    IsoSpeed,

    // GPS IFD
    GpsVersionId,
    GpsLatitudeRef,
    GpsLatitude,
    GpsLongitudeRef,
    GpsLongitude,
    GpsAltitudeRef,
    GpsAltitude,
    GpsTimeStamp,
    GpsSatellites,
    GpsStatus,
    GpsMeasureMode,
    GpsDop,
    GpsSpeedRef,
    GpsSpeed,
    GpsTrackRef,
    GpsTrack,
    GpsImgDirectionRef,
    GpsImgDirection,
    GpsMapDatum,
    GpsDestLatitudeRef,
    GpsDestLatitude,
    GpsDestLongitudeRef,
    GpsDestLongitude,
    GpsDestBearingRef,
    GpsDestBearing,
    GpsDestDistanceRef,
    GpsDestDistance,
    GpsProcessingMethod,
    GpsAreaInformation,
    GpsDateStamp,
    GpsDifferential,

    // Interoperability IFD
    InteroperabilityIndex,
    InteroperabilityVersion,

    // Thumbnail (IFD1)
    JpegInterchangeFormat,
    JpegInterchangeFormatLength,

    /// Any tag whose code is not recognized is kept as Unknown so data is not lost.
    Unknown(u16),
}

#[allow(unreachable_patterns)]
#[allow(clippy::match_overlapping_arm)]
impl Tag {
    /// Parse a raw u16 tag code into a `Tag`.
    pub fn from_u16(code: u16) -> Self {
        match code {
            0x0100 => Tag::ImageWidth,
            0x0101 => Tag::ImageLength,
            0x0102 => Tag::BitsPerSample,
            0x0103 => Tag::Compression,
            0x0106 => Tag::PhotometricInterpretation,
            0x010e => Tag::ImageDescription,
            0x010f => Tag::Make,
            0x0110 => Tag::Model,
            0x0111 => Tag::StripOffsets,
            0x0112 => Tag::Orientation,
            0x0115 => Tag::SamplesPerPixel,
            0x0116 => Tag::RowsPerStrip,
            0x0117 => Tag::StripByteCounts,
            0x011a => Tag::XResolution,
            0x011b => Tag::YResolution,
            0x011c => Tag::PlanarConfiguration,
            0x0128 => Tag::ResolutionUnit,
            0x012d => Tag::TransferFunction,
            0x0131 => Tag::Software,
            0x0132 => Tag::DateTime,
            0x013b => Tag::Artist,
            0x013e => Tag::WhitePoint,
            0x013f => Tag::PrimaryChromaticities,
            0x0201 => Tag::JpegInterchangeFormat,
            0x0202 => Tag::JpegInterchangeFormatLength,
            0x0211 => Tag::YCbCrCoefficients,
            0x0212 => Tag::YCbCrSubSampling,
            0x0213 => Tag::YCbCrPositioning,
            0x0214 => Tag::ReferenceBlackWhite,
            0x8298 => Tag::Copyright,
            0x829a => Tag::ExposureTime,
            0x829d => Tag::FNumber,
            0x8769 => Tag::ExifIfdPointer,
            0x8822 => Tag::ExposureProgram,
            0x8824 => Tag::SpectralSensitivity,
            0x8825 => Tag::GpsInfoIfdPointer,
            0x8827 => Tag::IsoSpeedRatings,
            0x8830 => Tag::SensitivityType,
            0x8831 => Tag::StandardOutputSensitivity,
            0x8832 => Tag::RecommendedExposureIndex,
            0x8833 => Tag::IsoSpeed,
            0x9000 => Tag::ExifVersion,
            0x9003 => Tag::DateTimeOriginal,
            0x9004 => Tag::DateTimeDigitized,
            0x9010 => Tag::OffsetTime,
            0x9011 => Tag::OffsetTimeOriginal,
            0x9012 => Tag::OffsetTimeDigitized,
            0x9101 => Tag::ComponentsConfiguration,
            0x9102 => Tag::CompressedBitsPerPixel,
            0x9201 => Tag::ShutterSpeedValue,
            0x9202 => Tag::ApertureValue,
            0x9203 => Tag::BrightnessValue,
            0x9204 => Tag::ExposureBiasValue,
            0x9205 => Tag::MaxApertureValue,
            0x9206 => Tag::SubjectDistance,
            0x9207 => Tag::MeteringMode,
            0x9208 => Tag::LightSource,
            0x9209 => Tag::Flash,
            0x920a => Tag::FocalLength,
            0x927c => Tag::MakerNote,
            0x9286 => Tag::UserComment,
            0x9290 => Tag::SubSecTime,
            0x9291 => Tag::SubSecTimeOriginal,
            0x9292 => Tag::SubSecTimeDigitized,
            0xa000 => Tag::FlashPixVersion,
            0xa001 => Tag::ColorSpace,
            0xa002 => Tag::PixelXDimension,
            0xa003 => Tag::PixelYDimension,
            0xa004 => Tag::RelatedSoundFile,
            0xa005 => Tag::InteroperabilityIfdPointer,
            0xa20b => Tag::FlashEnergy,
            0xa20e => Tag::FocalPlaneXResolution,
            0xa20f => Tag::FocalPlaneYResolution,
            0xa210 => Tag::FocalPlaneResolutionUnit,
            0xa214 => Tag::SubjectLocation,
            0xa215 => Tag::ExposureIndex,
            0xa217 => Tag::SensingMethod,
            0xa300 => Tag::FileSource,
            0xa301 => Tag::SceneType,
            0xa302 => Tag::CfaPattern,
            0xa401 => Tag::CustomRendered,
            0xa402 => Tag::ExposureMode,
            0xa403 => Tag::WhiteBalance,
            0xa404 => Tag::DigitalZoomRatio,
            0xa405 => Tag::FocalLengthIn35mmFilm,
            0xa406 => Tag::SceneCaptureType,
            0xa407 => Tag::GainControl,
            0xa408 => Tag::Contrast,
            0xa409 => Tag::Saturation,
            0xa40a => Tag::Sharpness,
            0xa40b => Tag::DeviceSettingDescription,
            0xa40c => Tag::SubjectDistanceRange,
            0xa420 => Tag::ImageUniqueId,
            0xa430 => Tag::CameraOwnerName,
            0xa431 => Tag::BodySerialNumber,
            0xa432 => Tag::LensSpecification,
            0xa433 => Tag::LensMake,
            0xa434 => Tag::LensModel,
            0xa435 => Tag::LensSerialNumber,

            // GPS IFD tags
            0x0000 => Tag::GpsVersionId,
            0x0001 => Tag::GpsLatitudeRef,
            0x0002 => Tag::GpsLatitude,
            0x0003 => Tag::GpsLongitudeRef,
            0x0004 => Tag::GpsLongitude,
            0x0005 => Tag::GpsAltitudeRef,
            0x0006 => Tag::GpsAltitude,
            0x0007 => Tag::GpsTimeStamp,
            0x0008 => Tag::GpsSatellites,
            0x0009 => Tag::GpsStatus,
            0x000a => Tag::GpsMeasureMode,
            0x000b => Tag::GpsDop,
            0x000c => Tag::GpsSpeedRef,
            0x000d => Tag::GpsSpeed,
            0x000e => Tag::GpsTrackRef,
            0x000f => Tag::GpsTrack,
            0x0010 => Tag::GpsImgDirectionRef,
            0x0011 => Tag::GpsImgDirection,
            0x0012 => Tag::GpsMapDatum,
            0x0013 => Tag::GpsDestLatitudeRef,
            0x0014 => Tag::GpsDestLatitude,
            0x0015 => Tag::GpsDestLongitudeRef,
            0x0016 => Tag::GpsDestLongitude,
            0x0017 => Tag::GpsDestBearingRef,
            0x0018 => Tag::GpsDestBearing,
            0x0019 => Tag::GpsDestDistanceRef,
            0x001a => Tag::GpsDestDistance,
            0x001b => Tag::GpsProcessingMethod,
            0x001c => Tag::GpsAreaInformation,
            0x001d => Tag::GpsDateStamp,
            0x001e => Tag::GpsDifferential,

            // Interoperability IFD tags
            0x0001 => Tag::InteroperabilityIndex,
            0x0002 => Tag::InteroperabilityVersion,

            other => Tag::Unknown(other),
        }
    }

    /// Returns the raw u16 code for this tag.
    pub fn code(self) -> u16 {
        match self {
            Tag::ImageWidth => 0x0100,
            Tag::ImageLength => 0x0101,
            Tag::BitsPerSample => 0x0102,
            Tag::Compression => 0x0103,
            Tag::PhotometricInterpretation => 0x0106,
            Tag::ImageDescription => 0x010e,
            Tag::Make => 0x010f,
            Tag::Model => 0x0110,
            Tag::StripOffsets => 0x0111,
            Tag::Orientation => 0x0112,
            Tag::SamplesPerPixel => 0x0115,
            Tag::RowsPerStrip => 0x0116,
            Tag::StripByteCounts => 0x0117,
            Tag::XResolution => 0x011a,
            Tag::YResolution => 0x011b,
            Tag::PlanarConfiguration => 0x011c,
            Tag::ResolutionUnit => 0x0128,
            Tag::TransferFunction => 0x012d,
            Tag::Software => 0x0131,
            Tag::DateTime => 0x0132,
            Tag::Artist => 0x013b,
            Tag::WhitePoint => 0x013e,
            Tag::PrimaryChromaticities => 0x013f,
            Tag::JpegInterchangeFormat => 0x0201,
            Tag::JpegInterchangeFormatLength => 0x0202,
            Tag::YCbCrCoefficients => 0x0211,
            Tag::YCbCrSubSampling => 0x0212,
            Tag::YCbCrPositioning => 0x0213,
            Tag::ReferenceBlackWhite => 0x0214,
            Tag::Copyright => 0x8298,
            Tag::ExposureTime => 0x829a,
            Tag::FNumber => 0x829d,
            Tag::ExifIfdPointer => 0x8769,
            Tag::ExposureProgram => 0x8822,
            Tag::SpectralSensitivity => 0x8824,
            Tag::GpsInfoIfdPointer => 0x8825,
            Tag::IsoSpeedRatings => 0x8827,
            Tag::SensitivityType => 0x8830,
            Tag::StandardOutputSensitivity => 0x8831,
            Tag::RecommendedExposureIndex => 0x8832,
            Tag::IsoSpeed => 0x8833,
            Tag::ExifVersion => 0x9000,
            Tag::DateTimeOriginal => 0x9003,
            Tag::DateTimeDigitized => 0x9004,
            Tag::OffsetTime => 0x9010,
            Tag::OffsetTimeOriginal => 0x9011,
            Tag::OffsetTimeDigitized => 0x9012,
            Tag::ComponentsConfiguration => 0x9101,
            Tag::CompressedBitsPerPixel => 0x9102,
            Tag::ShutterSpeedValue => 0x9201,
            Tag::ApertureValue => 0x9202,
            Tag::BrightnessValue => 0x9203,
            Tag::ExposureBiasValue => 0x9204,
            Tag::MaxApertureValue => 0x9205,
            Tag::SubjectDistance => 0x9206,
            Tag::MeteringMode => 0x9207,
            Tag::LightSource => 0x9208,
            Tag::Flash => 0x9209,
            Tag::FocalLength => 0x920a,
            Tag::MakerNote => 0x927c,
            Tag::UserComment => 0x9286,
            Tag::SubSecTime => 0x9290,
            Tag::SubSecTimeOriginal => 0x9291,
            Tag::SubSecTimeDigitized => 0x9292,
            Tag::FlashPixVersion => 0xa000,
            Tag::ColorSpace => 0xa001,
            Tag::PixelXDimension => 0xa002,
            Tag::PixelYDimension => 0xa003,
            Tag::RelatedSoundFile => 0xa004,
            Tag::InteroperabilityIfdPointer => 0xa005,
            Tag::FlashEnergy => 0xa20b,
            Tag::FocalPlaneXResolution => 0xa20e,
            Tag::FocalPlaneYResolution => 0xa20f,
            Tag::FocalPlaneResolutionUnit => 0xa210,
            Tag::SubjectLocation => 0xa214,
            Tag::ExposureIndex => 0xa215,
            Tag::SensingMethod => 0xa217,
            Tag::FileSource => 0xa300,
            Tag::SceneType => 0xa301,
            Tag::CfaPattern => 0xa302,
            Tag::CustomRendered => 0xa401,
            Tag::ExposureMode => 0xa402,
            Tag::WhiteBalance => 0xa403,
            Tag::DigitalZoomRatio => 0xa404,
            Tag::FocalLengthIn35mmFilm => 0xa405,
            Tag::SceneCaptureType => 0xa406,
            Tag::GainControl => 0xa407,
            Tag::Contrast => 0xa408,
            Tag::Saturation => 0xa409,
            Tag::Sharpness => 0xa40a,
            Tag::DeviceSettingDescription => 0xa40b,
            Tag::SubjectDistanceRange => 0xa40c,
            Tag::ImageUniqueId => 0xa420,
            Tag::CameraOwnerName => 0xa430,
            Tag::BodySerialNumber => 0xa431,
            Tag::LensSpecification => 0xa432,
            Tag::LensMake => 0xa433,
            Tag::LensModel => 0xa434,
            Tag::LensSerialNumber => 0xa435,
            Tag::GpsVersionId => 0x0000,
            Tag::GpsLatitudeRef => 0x0001,
            Tag::GpsLatitude => 0x0002,
            Tag::GpsLongitudeRef => 0x0003,
            Tag::GpsLongitude => 0x0004,
            Tag::GpsAltitudeRef => 0x0005,
            Tag::GpsAltitude => 0x0006,
            Tag::GpsTimeStamp => 0x0007,
            Tag::GpsSatellites => 0x0008,
            Tag::GpsStatus => 0x0009,
            Tag::GpsMeasureMode => 0x000a,
            Tag::GpsDop => 0x000b,
            Tag::GpsSpeedRef => 0x000c,
            Tag::GpsSpeed => 0x000d,
            Tag::GpsTrackRef => 0x000e,
            Tag::GpsTrack => 0x000f,
            Tag::GpsImgDirectionRef => 0x0010,
            Tag::GpsImgDirection => 0x0011,
            Tag::GpsMapDatum => 0x0012,
            Tag::GpsDestLatitudeRef => 0x0013,
            Tag::GpsDestLatitude => 0x0014,
            Tag::GpsDestLongitudeRef => 0x0015,
            Tag::GpsDestLongitude => 0x0016,
            Tag::GpsDestBearingRef => 0x0017,
            Tag::GpsDestBearing => 0x0018,
            Tag::GpsDestDistanceRef => 0x0019,
            Tag::GpsDestDistance => 0x001a,
            Tag::GpsProcessingMethod => 0x001b,
            Tag::GpsAreaInformation => 0x001c,
            Tag::GpsDateStamp => 0x001d,
            Tag::GpsDifferential => 0x001e,
            Tag::InteroperabilityIndex => 0x0001,
            Tag::InteroperabilityVersion => 0x0002,
            Tag::Unknown(code) => code,
        }
    }

    /// Returns a human-readable name for this tag.
    pub fn name(self) -> String {
        match self {
            Tag::ImageWidth => "ImageWidth".to_string(),
            Tag::ImageLength => "ImageLength".to_string(),
            Tag::BitsPerSample => "BitsPerSample".to_string(),
            Tag::Compression => "Compression".to_string(),
            Tag::PhotometricInterpretation => "PhotometricInterpretation".to_string(),
            Tag::ImageDescription => "ImageDescription".to_string(),
            Tag::Make => "Make".to_string(),
            Tag::Model => "Model".to_string(),
            Tag::StripOffsets => "StripOffsets".to_string(),
            Tag::Orientation => "Orientation".to_string(),
            Tag::SamplesPerPixel => "SamplesPerPixel".to_string(),
            Tag::RowsPerStrip => "RowsPerStrip".to_string(),
            Tag::StripByteCounts => "StripByteCounts".to_string(),
            Tag::XResolution => "XResolution".to_string(),
            Tag::YResolution => "YResolution".to_string(),
            Tag::PlanarConfiguration => "PlanarConfiguration".to_string(),
            Tag::ResolutionUnit => "ResolutionUnit".to_string(),
            Tag::TransferFunction => "TransferFunction".to_string(),
            Tag::Software => "Software".to_string(),
            Tag::DateTime => "DateTime".to_string(),
            Tag::Artist => "Artist".to_string(),
            Tag::WhitePoint => "WhitePoint".to_string(),
            Tag::PrimaryChromaticities => "PrimaryChromaticities".to_string(),
            Tag::Copyright => "Copyright".to_string(),
            Tag::ExposureTime => "ExposureTime".to_string(),
            Tag::FNumber => "FNumber".to_string(),
            Tag::ExifIfdPointer => "ExifIFDPointer".to_string(),
            Tag::GpsInfoIfdPointer => "GPSInfoIFDPointer".to_string(),
            Tag::ExifVersion => "ExifVersion".to_string(),
            Tag::DateTimeOriginal => "DateTimeOriginal".to_string(),
            Tag::DateTimeDigitized => "DateTimeDigitized".to_string(),
            Tag::OffsetTime => "OffsetTime".to_string(),
            Tag::OffsetTimeOriginal => "OffsetTimeOriginal".to_string(),
            Tag::OffsetTimeDigitized => "OffsetTimeDigitized".to_string(),
            Tag::ComponentsConfiguration => "ComponentsConfiguration".to_string(),
            Tag::CompressedBitsPerPixel => "CompressedBitsPerPixel".to_string(),
            Tag::ShutterSpeedValue => "ShutterSpeedValue".to_string(),
            Tag::ApertureValue => "ApertureValue".to_string(),
            Tag::BrightnessValue => "BrightnessValue".to_string(),
            Tag::ExposureBiasValue => "ExposureBiasValue".to_string(),
            Tag::MaxApertureValue => "MaxApertureValue".to_string(),
            Tag::SubjectDistance => "SubjectDistance".to_string(),
            Tag::MeteringMode => "MeteringMode".to_string(),
            Tag::LightSource => "LightSource".to_string(),
            Tag::Flash => "Flash".to_string(),
            Tag::FocalLength => "FocalLength".to_string(),
            Tag::MakerNote => "MakerNote".to_string(),
            Tag::UserComment => "UserComment".to_string(),
            Tag::FlashPixVersion => "FlashPixVersion".to_string(),
            Tag::ColorSpace => "ColorSpace".to_string(),
            Tag::PixelXDimension => "PixelXDimension".to_string(),
            Tag::PixelYDimension => "PixelYDimension".to_string(),
            Tag::IsoSpeedRatings => "ISOSpeedRatings".to_string(),
            Tag::ExposureProgram => "ExposureProgram".to_string(),
            Tag::ExposureMode => "ExposureMode".to_string(),
            Tag::WhiteBalance => "WhiteBalance".to_string(),
            Tag::FocalLengthIn35mmFilm => "FocalLengthIn35mmFilm".to_string(),
            Tag::SceneCaptureType => "SceneCaptureType".to_string(),
            Tag::Contrast => "Contrast".to_string(),
            Tag::Saturation => "Saturation".to_string(),
            Tag::Sharpness => "Sharpness".to_string(),
            Tag::DigitalZoomRatio => "DigitalZoomRatio".to_string(),
            Tag::ImageUniqueId => "ImageUniqueID".to_string(),
            Tag::LensModel => "LensModel".to_string(),
            Tag::LensMake => "LensMake".to_string(),
            Tag::GpsLatitudeRef => "GPSLatitudeRef".to_string(),
            Tag::GpsLatitude => "GPSLatitude".to_string(),
            Tag::GpsLongitudeRef => "GPSLongitudeRef".to_string(),
            Tag::GpsLongitude => "GPSLongitude".to_string(),
            Tag::GpsAltitudeRef => "GPSAltitudeRef".to_string(),
            Tag::GpsAltitude => "GPSAltitude".to_string(),
            Tag::GpsDateStamp => "GPSDateStamp".to_string(),
            Tag::JpegInterchangeFormat => "JPEGInterchangeFormat".to_string(),
            Tag::JpegInterchangeFormatLength => "JPEGInterchangeFormatLength".to_string(),
            Tag::Unknown(code) => format!("0x{:04X}", code),
            _ => format!("{:?}", self),
        }
    }
}

impl std::fmt::Display for Tag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
